# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lt_user_client
from lt_user_client.models.token_verify import TokenVerify  # noqa: E501
from lt_user_client.rest import ApiException


class TestTokenVerify(unittest.TestCase):
    """TokenVerify unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenVerify(self):
        """Test TokenVerify"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lt_user_client.models.token_verify.TokenVerify()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
