# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lt_user_client
from lt_user_client.api.api_token_api import ApiTokenApi  # noqa: E501
from lt_user_client.rest import ApiException


class TestApiTokenApi(unittest.TestCase):
    """ApiTokenApi unit test stubs"""

    def setUp(self):
        self.api = lt_user_client.api.api_token_api.ApiTokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_token_create(self):
        """Test case for api_token_create

        """
        pass

    def test_api_token_refresh_create(self):
        """Test case for api_token_refresh_create

        """
        pass

    def test_api_token_verify_create(self):
        """Test case for api_token_verify_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
