# coding: utf-8

"""
    Snippets API

    Test description  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@snippets.local
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lt_user_client
from lt_user_client.api.api_api import ApiApi  # noqa: E501
from lt_user_client.rest import ApiException


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = lt_user_client.api.api_api.ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_document_create(self):
        """Test case for api_document_create

        """
        pass

    def test_api_document_delete(self):
        """Test case for api_document_delete

        """
        pass

    def test_api_document_list(self):
        """Test case for api_document_list

        """
        pass

    def test_api_document_partial_update(self):
        """Test case for api_document_partial_update

        """
        pass

    def test_api_document_read(self):
        """Test case for api_document_read

        """
        pass

    def test_api_document_update(self):
        """Test case for api_document_update

        """
        pass

    def test_api_search_create(self):
        """Test case for api_search_create

        """
        pass

    def test_api_search_delete(self):
        """Test case for api_search_delete

        """
        pass

    def test_api_search_list(self):
        """Test case for api_search_list

        """
        pass

    def test_api_search_metadata(self):
        """Test case for api_search_metadata

        """
        pass

    def test_api_search_partial_update(self):
        """Test case for api_search_partial_update

        """
        pass

    def test_api_search_read(self):
        """Test case for api_search_read

        """
        pass

    def test_api_search_update(self):
        """Test case for api_search_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
