# coding: utf-8

"""
    Legaltext API

    API for Legaltext  # noqa: E501

    OpenAPI spec version: v1.1.1a0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lt_user_client
from lt_user_client.models.token_obtain_pair_request import TokenObtainPairRequest  # noqa: E501
from lt_user_client.rest import ApiException


class TestTokenObtainPairRequest(unittest.TestCase):
    """TokenObtainPairRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenObtainPairRequest(self):
        """Test TokenObtainPairRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lt_user_client.models.token_obtain_pair_request.TokenObtainPairRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
