# coding: utf-8

"""
    Legaltext API

    API for Legaltext  # noqa: E501

    OpenAPI spec version: v1.1.1a0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lt_user_client
from lt_user_client.api.api_api import ApiApi  # noqa: E501
from lt_user_client.rest import ApiException


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_category_create(self):
        """Test case for api_category_create

        """
        pass

    def test_api_category_destroy(self):
        """Test case for api_category_destroy

        """
        pass

    def test_api_category_list(self):
        """Test case for api_category_list

        """
        pass

    def test_api_category_partial_update(self):
        """Test case for api_category_partial_update

        """
        pass

    def test_api_category_retrieve(self):
        """Test case for api_category_retrieve

        """
        pass

    def test_api_category_update(self):
        """Test case for api_category_update

        """
        pass

    def test_api_document_create(self):
        """Test case for api_document_create

        """
        pass

    def test_api_document_destroy(self):
        """Test case for api_document_destroy

        """
        pass

    def test_api_document_list(self):
        """Test case for api_document_list

        """
        pass

    def test_api_document_partial_update(self):
        """Test case for api_document_partial_update

        """
        pass

    def test_api_document_retrieve(self):
        """Test case for api_document_retrieve

        """
        pass

    def test_api_document_type_create(self):
        """Test case for api_document_type_create

        """
        pass

    def test_api_document_type_destroy(self):
        """Test case for api_document_type_destroy

        """
        pass

    def test_api_document_type_list(self):
        """Test case for api_document_type_list

        """
        pass

    def test_api_document_type_partial_update(self):
        """Test case for api_document_type_partial_update

        """
        pass

    def test_api_document_type_retrieve(self):
        """Test case for api_document_type_retrieve

        """
        pass

    def test_api_document_type_update(self):
        """Test case for api_document_type_update

        """
        pass

    def test_api_document_update(self):
        """Test case for api_document_update

        """
        pass

    def test_api_search_create(self):
        """Test case for api_search_create

        """
        pass

    def test_api_search_destroy(self):
        """Test case for api_search_destroy

        """
        pass

    def test_api_search_list(self):
        """Test case for api_search_list

        """
        pass

    def test_api_search_metadata_retrieve(self):
        """Test case for api_search_metadata_retrieve

        """
        pass

    def test_api_search_partial_update(self):
        """Test case for api_search_partial_update

        """
        pass

    def test_api_search_retrieve(self):
        """Test case for api_search_retrieve

        """
        pass

    def test_api_search_update(self):
        """Test case for api_search_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
