# coding: utf-8

"""
    Legaltext API

    API for Legaltext  # noqa: E501

    OpenAPI spec version: v1.1.1a0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lt_user_client
from lt_user_client.models.paginated_document_list import PaginatedDocumentList  # noqa: E501
from lt_user_client.rest import ApiException


class TestPaginatedDocumentList(unittest.TestCase):
    """PaginatedDocumentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedDocumentList(self):
        """Test PaginatedDocumentList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lt_user_client.models.paginated_document_list.PaginatedDocumentList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
