# coding: utf-8

"""
    Legaltext API

    API for Legaltext  # noqa: E501

    OpenAPI spec version: v1.1.1a0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CategoryRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'description': 'str',
        'icon': 'str',
        'color': 'str',
        'parent': 'int'
    }

    attribute_map = {
        'title': 'title',
        'description': 'description',
        'icon': 'icon',
        'color': 'color',
        'parent': 'parent'
    }

    def __init__(self, title=None, description=None, icon=None, color=None, parent=None):  # noqa: E501
        """CategoryRequest - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._description = None
        self._icon = None
        self._color = None
        self._parent = None
        self.discriminator = None
        self.title = title
        self.description = description
        if icon is not None:
            self.icon = icon
        if color is not None:
            self.color = color
        if parent is not None:
            self.parent = parent

    @property
    def title(self):
        """Gets the title of this CategoryRequest.  # noqa: E501


        :return: The title of this CategoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CategoryRequest.


        :param title: The title of this CategoryRequest.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self):
        """Gets the description of this CategoryRequest.  # noqa: E501


        :return: The description of this CategoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CategoryRequest.


        :param description: The description of this CategoryRequest.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def icon(self):
        """Gets the icon of this CategoryRequest.  # noqa: E501


        :return: The icon of this CategoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """Sets the icon of this CategoryRequest.


        :param icon: The icon of this CategoryRequest.  # noqa: E501
        :type: str
        """

        self._icon = icon

    @property
    def color(self):
        """Gets the color of this CategoryRequest.  # noqa: E501


        :return: The color of this CategoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this CategoryRequest.


        :param color: The color of this CategoryRequest.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def parent(self):
        """Gets the parent of this CategoryRequest.  # noqa: E501


        :return: The parent of this CategoryRequest.  # noqa: E501
        :rtype: int
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this CategoryRequest.


        :param parent: The parent of this CategoryRequest.  # noqa: E501
        :type: int
        """

        self._parent = parent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CategoryRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CategoryRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
