# coding: utf-8

"""
    Legaltext API

    API for Legaltext  # noqa: E501

    OpenAPI spec version: v1.1.1a0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Document(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'file': 'str',
        'title': 'str',
        'description': 'str',
        '_date': 'date',
        'display_html': 'str',
        'created_at': 'datetime',
        'published': 'bool',
        'category': 'int',
        'document_type': 'int',
        'publisher': 'int',
        'related_documents': 'list[int]',
        'sites': 'list[int]'
    }

    attribute_map = {
        'id': 'id',
        'file': 'file',
        'title': 'title',
        'description': 'description',
        '_date': 'date',
        'display_html': 'display_html',
        'created_at': 'created_at',
        'published': 'published',
        'category': 'category',
        'document_type': 'document_type',
        'publisher': 'publisher',
        'related_documents': 'related_documents',
        'sites': 'sites'
    }

    def __init__(self, id=None, file=None, title=None, description=None, _date=None, display_html=None, created_at=None, published=None, category=None, document_type=None, publisher=None, related_documents=None, sites=None):  # noqa: E501
        """Document - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._file = None
        self._title = None
        self._description = None
        self.__date = None
        self._display_html = None
        self._created_at = None
        self._published = None
        self._category = None
        self._document_type = None
        self._publisher = None
        self._related_documents = None
        self._sites = None
        self.discriminator = None
        self.id = id
        self.file = file
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        self._date = _date
        self.display_html = display_html
        self.created_at = created_at
        if published is not None:
            self.published = published
        self.category = category
        if document_type is not None:
            self.document_type = document_type
        if publisher is not None:
            self.publisher = publisher
        if related_documents is not None:
            self.related_documents = related_documents
        self.sites = sites

    @property
    def id(self):
        """Gets the id of this Document.  # noqa: E501


        :return: The id of this Document.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Document.


        :param id: The id of this Document.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def file(self):
        """Gets the file of this Document.  # noqa: E501


        :return: The file of this Document.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this Document.


        :param file: The file of this Document.  # noqa: E501
        :type: str
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file

    @property
    def title(self):
        """Gets the title of this Document.  # noqa: E501


        :return: The title of this Document.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Document.


        :param title: The title of this Document.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this Document.  # noqa: E501


        :return: The description of this Document.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Document.


        :param description: The description of this Document.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def _date(self):
        """Gets the _date of this Document.  # noqa: E501


        :return: The _date of this Document.  # noqa: E501
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this Document.


        :param _date: The _date of this Document.  # noqa: E501
        :type: date
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def display_html(self):
        """Gets the display_html of this Document.  # noqa: E501

        The HTML to display the document. Use the following placeholders: {title}, {description}, {file_url}  # noqa: E501

        :return: The display_html of this Document.  # noqa: E501
        :rtype: str
        """
        return self._display_html

    @display_html.setter
    def display_html(self, display_html):
        """Sets the display_html of this Document.

        The HTML to display the document. Use the following placeholders: {title}, {description}, {file_url}  # noqa: E501

        :param display_html: The display_html of this Document.  # noqa: E501
        :type: str
        """
        if display_html is None:
            raise ValueError("Invalid value for `display_html`, must not be `None`")  # noqa: E501

        self._display_html = display_html

    @property
    def created_at(self):
        """Gets the created_at of this Document.  # noqa: E501


        :return: The created_at of this Document.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Document.


        :param created_at: The created_at of this Document.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def published(self):
        """Gets the published of this Document.  # noqa: E501


        :return: The published of this Document.  # noqa: E501
        :rtype: bool
        """
        return self._published

    @published.setter
    def published(self, published):
        """Sets the published of this Document.


        :param published: The published of this Document.  # noqa: E501
        :type: bool
        """

        self._published = published

    @property
    def category(self):
        """Gets the category of this Document.  # noqa: E501


        :return: The category of this Document.  # noqa: E501
        :rtype: int
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this Document.


        :param category: The category of this Document.  # noqa: E501
        :type: int
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category

    @property
    def document_type(self):
        """Gets the document_type of this Document.  # noqa: E501


        :return: The document_type of this Document.  # noqa: E501
        :rtype: int
        """
        return self._document_type

    @document_type.setter
    def document_type(self, document_type):
        """Sets the document_type of this Document.


        :param document_type: The document_type of this Document.  # noqa: E501
        :type: int
        """

        self._document_type = document_type

    @property
    def publisher(self):
        """Gets the publisher of this Document.  # noqa: E501


        :return: The publisher of this Document.  # noqa: E501
        :rtype: int
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher):
        """Sets the publisher of this Document.


        :param publisher: The publisher of this Document.  # noqa: E501
        :type: int
        """

        self._publisher = publisher

    @property
    def related_documents(self):
        """Gets the related_documents of this Document.  # noqa: E501


        :return: The related_documents of this Document.  # noqa: E501
        :rtype: list[int]
        """
        return self._related_documents

    @related_documents.setter
    def related_documents(self, related_documents):
        """Sets the related_documents of this Document.


        :param related_documents: The related_documents of this Document.  # noqa: E501
        :type: list[int]
        """

        self._related_documents = related_documents

    @property
    def sites(self):
        """Gets the sites of this Document.  # noqa: E501


        :return: The sites of this Document.  # noqa: E501
        :rtype: list[int]
        """
        return self._sites

    @sites.setter
    def sites(self, sites):
        """Sets the sites of this Document.


        :param sites: The sites of this Document.  # noqa: E501
        :type: list[int]
        """
        if sites is None:
            raise ValueError("Invalid value for `sites`, must not be `None`")  # noqa: E501

        self._sites = sites

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Document, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Document):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
